# Generated by Django 4.0.2 on 2022-02-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdetailsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('book_name', models.CharField(max_length=90)),
                ('book_price', models.IntegerField(max_length=10)),
                ('book_description', models.CharField(max_length=100)),
            ],
        ),
    ]
