# Generated by Django 4.0.2 on 2022-02-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetailsmodel',
            name='book_price',
            field=models.IntegerField(),
        ),
    ]
