# Generated by Django 4.0.2 on 2022-02-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_alter_bookdetailsmodel_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetailsmodel',
            name='profile_pic',
            field=models.IntegerField(),
        ),
    ]
