# Generated by Django 4.0.2 on 2022-02-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_alter_bookdetailsmodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetailsmodel',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
