# Generated by Django 4.0.2 on 2022-02-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_alter_bookdetailsmodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetailsmodel',
            name='book_price',
            field=models.FloatField(),
        ),
    ]
