# Generated by Django 4.0.2 on 2022-02-04 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_alter_bookdetailsmodel_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetailsmodel',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='bookdetailsmodel',
            table='bookapp_bookdetailsmodel',
        ),
    ]
