# Generated by Django 4.0.2 on 2022-02-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_alter_bookdetailsmodel_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookdetailsmodel',
            table=None,
        ),
    ]
