# Generated by Django 4.0.2 on 2022-02-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_alter_bookdetailsmodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetailsmodel',
            name='book_description',
            field=models.CharField(max_length=255),
        ),
    ]
